# Generated by Django 4.1.6 on 2023-04-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_app', '0002_forum_alter_comment_form_delete_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='form',
        ),
        migrations.AddField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='a_app.forum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='istifadeci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to=settings.AUTH_USER_MODEL),
        ),
    ]
