# Generated by Django 4.1.6 on 2023-05-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0006_useranswercard_delete_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswercard',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_useranswercards', to='a_app.exam'),
            preserve_default=False,
        ),
    ]
